---
title: "publications_check"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("googledrive")
library(googledrive)
# devtools::install_github("tidyverse/googlesheets4")
library(googlesheets4)

library(synapser)
synLogin()
```

```{r}
csbc_allPubs <- googledrive::drive_get( id = "19PehzZ12YOqkesco2hKRuWyEqYtHGnFM_5WuHPef1O0")
# sheets_get(csbc_allPubs)
csbc_allPubs_df <- read_sheet(csbc_allPubs)

csbc_urls <- csbc_allPubs_df$`Manifest link`
names(csbc_urls) <- csbc_allPubs_df$`CSBC PSON center`

check_sheet_col_NAs <- function(sheet, sheet_col) {
  if ( any(is.na(sheet[[sheet_col]])) ) { #if any NAs
    len_col <- length(sheet[[sheet_col]])
    len_col_notNA <- length(na.omit(sheet[[sheet_col]]))
    na_message <- paste0(len_col_notNA, " out of ", len_col, " rows in ", sheet_col ," are filled out")
    return(na_message)
  }
  else print(paste0(sheet_col, " is all filled out"))
}

```
```{r}
df <- data.frame(matrix(ncol = 7, nrow = 39))
colnames(df) <- c("CSBC PSON center", "Institution", "Total Number of Publications", "Number of Disease focus filled out",  "Number of Tissue or Organ filled out",  "Number of Experimental Strategy filled out",  "Number of Theme filled out")


get_sheet_col_notNAs <- function(sheet, sheet_col) {
  if ( any(is.na(sheet[[sheet_col]])) ) { #if any NAs
    len_col_notNA <- length(na.omit(sheet[[sheet_col]]))
    return(len_col_notNA)
  }
  else return(length(na.omit(sheet[[sheet_col]])))
}

get_sheet_col_total <- function(sheet, sheet_col) {
  if ( any(is.na(sheet[[sheet_col]])) ) { #if any NAs
    len_col <- length(sheet[[sheet_col]])
    return(len_col)
  }
  else return( length(sheet[[sheet_col]]) )
}

for (i in seq_along(csbc_urls) ) { ### may be too many queries, may have to split it up  # 12:39
  print(csbc_urls[[i]])
  sheet <- read_sheet(csbc_urls[[i]])
  synID <- names(csbc_urls[i])
  institutions <- synGetAnnotations(synID)$institution[[1]]
  df[i, 1] <- synID
  df[i, 2] <- institutions
  
  ### if they added things to the top of the sheet
  for (y in seq_along(sheet[[1]]) ) { 
    if (sheet[[1]][y] == "Title" & !is.na(sheet[[1]][y])) {
      colnames(sheet) <- c(unlist(sheet[y,]))
      sheet <- sheet[-c(1:y),] #cuts off added space
      
      total <- get_sheet_col_total(sheet, 'Disease focus')
      df[i,3] <- total
      
      diseasNum <- get_sheet_col_notNAs(sheet, 'Disease focus')
      df[i,4] <- diseasNum
      tissueNum <- get_sheet_col_notNAs(sheet, 'Tissue or Organ')
      df[i,5] <- tissueNum
      statNum <- get_sheet_col_notNAs(sheet, 'Experimental Strategy')
      df[i,6] <- statNum
      themeNum <- get_sheet_col_notNAs(sheet, 'Theme')
      df[i,7] <- themeNum
      
      
    } else { 
      total <- get_sheet_col_total(sheet, 'Disease focus')
      df[i,3] <- total
      
      diseasNum <- get_sheet_col_notNAs(sheet, 'Disease focus')
      df[i,4] <- diseasNum
      tissueNum <- get_sheet_col_notNAs(sheet, 'Tissue or Organ')
      df[i,5] <- tissueNum
      statNum <- get_sheet_col_notNAs(sheet, 'Experimental Strategy')
      df[i,6] <- statNum
      themeNum <- get_sheet_col_notNAs(sheet, 'Theme')
      df[i,7] <- themeNum
      
    }
    
  }
}

```
```{r}
df_merged <- dplyr::inner_join(df, csbc_allPubs_df, by = "CSBC PSON center")

write.csv(df_merged, file = "CSBC_publications_status2.csv", row.names = FALSE)
```

