---
title: "R Notebook"
output: html_notebook
---

```{r}
merged_grants_df <- dccvalidator::get_synapse_table("syn21918972", syn)
merged_projects_df <- dccvalidator::get_synapse_table("syn21868602", syn)
merged_datasets_df <- dccvalidator::get_synapse_table("syn21897968", syn)
merged_publications_df <- dccvalidator::get_synapse_table("syn21868591", syn)
merged_tools_df <- dccvalidator::get_synapse_table("syn21930566", syn)
db_theme_df <- dccvalidator::get_synapse_table("syn21630087", syn)

property_cols <- c("createdOn", "createdBy",
                   "modifiedOn", "modifiedBy",
                   "currentVersion")
```


```{r}
json_to_list <- function(json_str) {
  if (!is.na(json_str)) {
    jsonlite::fromJSON(json_str)
  } else {
    vector(mode = "character")
  }
}
```

```{r}
consortium_grants <- merged_grants_df %>% 
  select(grantId, consortium) %>% 
  group_by(consortium) %>% 
  tally(name = "grants")

consortium_grants
```

```{r}
theme_grants <- merged_grants_df %>% 
  select(consortium, grantId, theme) %>% 
  filter(theme != "[]") %>% 
  mutate(theme = map(theme, json_to_list)) %>% 
  unnest("theme") %>% 
  left_join(select(db_theme_df, theme = displayName, 
                   themeDescription = description)) %>% 
  filter(!is.na(themeDescription)) %>%  
  group_by(theme, themeDescription, consortium) %>% 
  tally(name = "grants") %>% 
  ungroup() %>% 
  gather(groupBy, totalCount, grants)

theme_grants
```

```{r}
ct_counts_syntable <- update_synapse_table("syn21649281", theme_grants, syn, syntab)
```

```{r}
# consortium_projs <- merged_projects_df %>% 
#   select(projectId, consortium) %>% 
#   mutate_all(~ str_trim(.)) %>% 
#   group_by(consortium) %>%
#   tally(name = "projects") %>%
#   I
# 
# consortium_projs
```

```{r}
# consortiumtheme_projs <- merged_projects_df %>% 
#  select(projectId, consortium, theme) %>% 
#   filter(theme != "[]") %>% 
#   mutate(theme = map(theme, json_to_list)) %>% 
#   unnest("theme") %>% 
#   left_join(select(db_theme_df, theme = displayName, 
#                    themeDescription = description)) %>% 
#   filter(!is.na(themeDescription)) %>%  
#   mutate(groupBy = "projects") %>% 
#   group_by(theme, themeDescription, consortium, groupBy) %>% 
#   tally(name = "totalCount") %>% 
#   ungroup()
# 
# consortiumtheme_projs
```

```{r}
# ct_counts_syntable <- update_synapse_table("syn21649281", consortiumtheme_projs, syn, syntab)
```

```{r}
theme_pubs <- merged_publications_df %>% 
  select(publicationId, theme) %>% 
  filter(theme != "[]") %>% 
  mutate(theme = map(theme, json_to_list)) %>% 
  unnest("theme") %>% 
  left_join(select(db_theme_df, theme = displayName, 
                   themeDescription = description)) %>% 
  filter(!is.na(themeDescription)) %>%  
  group_by(theme, themeDescription) %>% 
  tally(name = "publications") %>% 
  ungroup()

theme_pubs
```

```{r}
theme_dsets <- merged_datasets_df %>% 
  select(publicationId, theme) %>% 
  filter(theme != "[]") %>% 
  mutate(theme = map(theme, json_to_list)) %>% 
  unnest("theme") %>% 
  left_join(select(db_theme_df, theme = displayName, 
                   themeDescription = description)) %>% 
  filter(!is.na(themeDescription)) %>%  
  group_by(theme, themeDescription) %>% 
  tally(name = "datasets") %>% 
  ungroup()

theme_dsets
```

```{r}
theme_tools <- merged_tools_df %>% 
  select(publicationId, theme) %>% 
  filter(theme != "[]") %>% 
  mutate(theme = map(theme, json_to_list)) %>% 
  unnest("theme") %>% 
  left_join(select(db_theme_df, theme = displayName, 
                   themeDescription = description)) %>% 
  filter(!is.na(themeDescription)) %>%  
  group_by(theme, themeDescription) %>% 
  tally(name = "tools") %>% 
  ungroup()

theme_tools
```

```{r}
theme_counts <- theme_dsets %>% 
  left_join(theme_pubs) %>% 
  left_join(theme_tools) %>% 
  replace_na(list(tools = 0)) %>% 
  gather(groupBy, totalCount, -theme, -themeDescription) %>% 
  filter(theme != "Computational Resource")

theme_counts
```


```{r}
theme_counts_syntable <- update_synapse_table("syn21639584", theme_counts, syn, syntab)
```


```{r}
consortium_counts <- consortium_grants %>% 
  # left_join(consortium_projs) %>% 
  gather(groupBy, totalCount, -consortium)

consortium_counts
```

```{r}
consortium_counts_syntable <- update_synapse_table("syn21641485", consortium_counts, syn, syntab)
```
