---
title: "CSBC/PS-ON Portal ETL"
output: html_notebook
---

The code in this notebook is used to take data from tables in the [CSBC/PS-ON Portal DB](https://www.synapse.org/#!Synapse:syn21498902/wiki/600349) and recombine them into denormalized, production tables hosted in the [CSBC/PS-ON Knowledge Portal Synapse project](https://www.synapse.org/csbcpson). 

```{r}
library(synapser)
library(syndccutils)
# Sys.setenv(RETICULATE_PYTHON="~/anaconda/envs/csbc-pson-dcc/bin/python")
# library(reticulate)
library(tidyverse)

source("../R/summary_viz.R")
source("../R/synapse_db.R")

synLogin()
# use_condaenv("csbc-pson-dcc")
# synapseclient <- reticulate::import("synapseclient")
# syn <- synapseclient$Synapse()
# syn$login()
```

```{r}
db_consortium_df <- get_table_df("syn21630133", cache = FALSE)
db_theme_df <- get_table_df("syn21630087", cache = FALSE)
db_grant_df <- get_table_df("syn21639712", cache = FALSE)
db_institution_df <- get_table_df("syn21905891", cache = FALSE)

db_theme_grant <- get_table_df("syn21639726", cache = FALSE)
db_institution_grant <- get_table_df("syn21905912", cache = FALSE)
db_person_grant <- get_table_df("syn21905932", cache = FALSE)

property_cols <- c("createdOn", "createdBy",
                   "modifiedOn", "modifiedBy",
                   "currentVersion")
```

## Grants - merged table

```{r}
merged_grant_df <- db_grant_df %>% 
  select(-one_of(property_cols)) %>% 
  rename(grantId = id, grantName = name) %>%
  left_join(db_theme_grant, by = "grantId") %>% 
  left_join(db_institution_grant, by = "grantId") %>% 
  left_join(db_person_grant, by = "grantId") %>% 
  left_join(
    db_theme_df %>% 
      select(themeId = id, theme = displayName),
    by = "themeId"
  ) %>% 
  left_join(
    db_consortium_df %>% 
      select(consortiumId = id, consortium = displayName)
  ) %>% 
  left_join(
    db_institution_df %>% 
      select(institutionId = id, institution = fullName)
  ) %>% 
  select(grantId, grantName, grantNumber, consortium, theme,
         institution, investigator = person,
         abstract = description, grantType) %>% 
  distinct() %>% 
  I

merged_grant_df
```

```{r}
merged_formatted_grant_df <- merged_grant_df %>%
  filter(!is.na(grantName)) %>%
  group_by(grantId, grantName, abstract, grantType) %>%
  summarize(institution = str_c(unique(institution), collapse = " | "),
            investigator = str_c(unique(investigator), collapse = ", "),
            theme = str_c(unique(theme), collapse = ", "),
            consortium = str_c(unique(consortium), collapse = ", ")) %>%
  ungroup() %>%
  distinct()

merged_formatted_grant_df
```

```{r}
# initial table creation (synIDs need to be integers)
# merged_grant_syntable <- merged_formatted_grant_df %>% 
#   mutate_at(vars(contains("Id")), ~ str_replace(., "syn", "")) %>% 
#   synBuildTable("Portal - Grants Merged", "syn7080714", .) %>% 
#   synStore()

# update/overwrite the table
merged_grant_syntable <- merged_formatted_grant_df %>% 
  # mutate(id = grantName) %>% 
  update_table("syn21918972", .)
```


## Projects - merged table

```{r}
db_project_df <- get_table_df("syn21645147", cache = FALSE)
db_description_project <- get_table_df("syn21868407", cache = FALSE)
```

```{r}
merged_project_df <- db_project_df %>% 
  rename(projectId = id, projectName = name) %>%
  left_join(
    db_description_project, by = "projectId"
  ) %>% 
  left_join(
    db_grant_df %>% 
      select(grantId = id, grantName = name, grantType, consortiumId), 
    by = "grantId"
  ) %>% 
  left_join(db_theme_grant, by = "grantId") %>% 
  left_join(
    db_theme_df %>% 
      select(themeId = id, theme = displayName),
    by = "themeId"
  ) %>% 
  left_join(
    db_consortium_df %>% 
      select(consortiumId = id, consortium = displayName)
  ) %>% 
  select(projectId, projectName = displayName, description, 
         theme, grantName, consortium, grantType) %>%
  distinct()

merged_project_df
```

```{r}
merged_formatted_project_df <- merged_project_df %>%
  filter(!is.na(grantName)) %>%
  group_by(projectName, description) %>%
  summarize(grantName = str_c(unique(grantName), collapse = ", "),
            grantType = str_c(unique(grantType), collapse = ", "),
            theme = str_c(unique(theme), collapse = ", "),
            consortium = str_c(unique(consortium), collapse = ", ")) %>%
  ungroup() %>%
  # rowwise() %>% 
  # mutate_at(proj_list_cols, ~ csv_str_to_json(.)) %>%
  # ungroup() %>% 
  distinct()
```

```{r}
# initial table creation (synIDs need to be integers)
# merged_proj_syntable <- merged_formatted_proj_df %>% 
#   mutate_at(vars(contains("Id")), ~ str_replace(., "syn", "")) %>% 
#   synBuildTable("Portal - projs Merged", "syn7080714", .) %>% 
#   synStore()

# update/overwrite the table
merged_proj_syntable <- merged_formatted_proj_df %>% 
  # mutate(id = projName) %>% 
  update_table("syn21868602", .)
```

## Datasets - merged table

```{r}
db_dataset_df <- get_table_df("syn21889931", cache = FALSE)
db_description_dataset <- get_table_df("syn21895659", cache = FALSE)
db_link_dataset <- get_table_df("syn21895656", cache = FALSE)
db_dataset_pub <- get_table_df("syn21895676", cache = FALSE)

db_pub_df <- get_table_df("syn21650536", cache = FALSE)
```

```{r}
merged_dataset_df <- db_dataset_df %>% 
  select(-one_of(property_cols)) %>% 
  rename(datasetId = id, datasetName = fullName) %>%
  mutate(datasetName = ifelse(datasetName == "NA", displayName, datasetName)) %>% 
  left_join(db_description_dataset, by = "datasetId") %>% 
  left_join(db_link_dataset, by = "datasetId") %>%
  left_join(db_dataset_pub, by = "datasetId") %>% 
  left_join(
    db_grant_df %>% 
      select(grantId = id, grantName = name, grantType, consortiumId), 
    by = "grantId"
  ) %>% 
  left_join(db_theme_grant, by = "grantId") %>% 
  left_join(
    db_theme_df %>% 
      select(themeId = id, theme = displayName),
    by = "themeId"
  ) %>% 
  left_join(
    db_consortium_df %>% 
      select(consortiumId = id, consortium = displayName)
  ) %>% 
  left_join(
    db_pub_df %>% 
      select(publicationId = id, publicationTitle = title, pubMedUrl)
  ) %>% 
  mutate(pubMedId = str_extract(pubMedUrl, "[0-9].*")) %>%
  mutate_all(~ ifelse(str_detect(., "^NA$"), NA, .)) %>% 
  mutate(externalLink = glue::glue("[{source}:{displayName}]({url})")) %>% 
  mutate(pubMedLink = glue::glue("[{publicationTitle} (PMID:{pubMedId})]({pubMedUrl})")) %>% 
  mutate(tumorType = "", assay = "", species = "") %>% 
  mutate(overallDesign = ifelse(overallDesign == "NA", NA, overallDesign)) %>% 
  select(datasetId, datasetName, description, publicationTitle, overallDesign, 
         tumorType, assay, species, externalLink, 
         publicationId, publication = pubMedLink,
         grantId, grantName, consortium, grantType, theme) %>% 
  mutate_all(~ ifelse(. == "[NA (PMID:NA)](NA)", NA, .)) %>% 
  distinct()

merged_dataset_df
```

```{r}
merged_formatted_dataset_df <- merged_dataset_df %>%
  filter(!is.na(grantName)) %>%
  group_by(datasetId, datasetName, description, overallDesign, externalLink, 
           publicationId, publicationTitle, publication, ) %>%
  summarize(grantId = str_c(unique(grantId), collapse = ", "),
            grantName = str_c(unique(grantName), collapse = ", "),
            tumorType = str_c(unique(tumorType), collapse = ", "),
            assay = str_c(unique(assay), collapse = ", "),
            species = str_c(unique(species), collapse = ", "),
            grantType = str_c(unique(grantType), collapse = ", "),
            theme = str_c(unique(theme), collapse = ", "),
            consortium = str_c(unique(consortium), collapse = ", ")) %>%
  ungroup() %>%
  # rowwise() %>% 
  # mutate_at(pub_list_cols, ~ csv_str_to_json(.)) %>%
  # ungroup() %>% 
  distinct()

merged_formatted_dataset_df
```

```{r}
# initial table creation (synIDs need to be integers)
# merged_dataset_syntable <- merged_formatted_dataset_df %>% 
#   mutate_at(vars(contains("Id")), ~ str_replace(., "syn", "")) %>% 
#   synBuildTable("Portal - datasets Merged", "syn7080714", .) %>% 
#   synStore()

merged_dataset_table <- update_table("syn21897968", merged_formatted_dataset_df)
```

## Publications - merged table

```{r}
db_pub_df <- get_table_df("syn21650536", cache = FALSE)
db_grant_pub <- get_table_df("syn21682660", cache = FALSE)
db_person_pub <- get_table_df("syn21792842", cache = FALSE)
db_assay_pub <- get_table_df("syn21794722", cache = FALSE)
db_tissue_pub <- get_table_df("syn21795296", cache = FALSE)
db_tumortype_pub <- get_table_df("syn21795742", cache = FALSE)
db_link_pub <- get_table_df("syn21868571", cache = FALSE)
db_dataset_pub <- get_table_df("syn21895676", cache = FALSE)

db_dataset_df <- get_table_df("syn21889931", cache = FALSE)
```

```{r}
pub_list_cols <- c(
  "grantName", 
  "assay", 
  "tissue", 
  "tumorType", 
  "grantType", 
  "theme", 
  "consortium"
)
```


```{r, warning=FALSE, message=FALSE}
merged_pub_df <- db_pub_df %>% 
  select(-one_of(property_cols)) %>% 
  rename(publicationId = id, publicationTitle = title) %>%
  left_join(db_grant_pub, by = "publicationId") %>% 
  left_join(db_person_pub, by = "publicationId") %>% 
  left_join(db_assay_pub, by = "publicationId") %>% 
  left_join(db_tissue_pub, by = "publicationId") %>% 
  left_join(db_tumortype_pub, by = "publicationId") %>% 
  left_join(db_link_pub, by = "publicationId") %>% 
  left_join(db_dataset_pub, by = "publicationId") %>% 
  left_join(
    db_grant_df %>% 
      select(grantId = id, grantName = name, grantType, consortiumId), 
    by = "grantId"
  ) %>% 
  left_join(db_theme_grant, by = "grantId") %>% 
  left_join(
    db_theme_df %>% 
      select(themeId = id, theme = displayName),
    by = "themeId"
  ) %>% 
  left_join(
    db_consortium_df %>% 
      select(consortiumId = id, consortium = displayName)
  ) %>% 
  left_join(
    db_dataset_df %>% 
      select(datasetId = id, dataset = displayName)
  ) %>% 
  select(publicationId, doi, journal, 
         pubMedUrl, publicationTitle, publicationYear, keywords,
         authors = person, assay, tissue, tumorType,
         consortium, grantName, theme, grantType, datasetId, dataset) %>% 
  distinct() %>% 
  mutate_all(~ ifelse(str_detect(., "Not Applicable"), NA, .)) %>% 
  mutate_all(~ ifelse(str_detect(., "^NA$"), NA, .))

merged_pub_df
```

```{r}
merged_formatted_pub_df <- merged_pub_df %>%
  filter(!is.na(grantName)) %>%
  group_by(publicationId, doi, journal, pubMedUrl, 
           publicationTitle, publicationYear, keywords) %>%
  summarize(grantName = str_c(unique(grantName), collapse = ", "),
            authors = str_c(unique(authors), collapse = ", "),
            assay = str_c(unique(assay), collapse = ", "),
            tissue = str_c(unique(tissue), collapse = ", "),
            tumorType = str_c(unique(tumorType), collapse = ", "),
            grantType = str_c(unique(grantType), collapse = ", "),
            theme = str_c(unique(theme), collapse = ", "),
            consortium = str_c(unique(consortium), collapse = ", "),
            datasetId = str_c(unique(datasetId), collapse = ", "),
            dataset = str_c(unique(dataset), collapse = ", ")
            ) %>%
  ungroup() %>%
  # rowwise() %>% 
  # mutate_at(pub_list_cols, ~ csv_str_to_json(.)) %>%
  # ungroup() %>% 
  distinct()

merged_formatted_pub_df
```

```{r}
# merged_pub_cols <- list(
#   Column(name = 'authors', columnType = 'LARGETEXT'),
#   Column(name = 'doi', columnType = 'STRING', maximumSize = 29),
#   Column(name = 'journal', columnType = 'STRING', maximumSize = 39),
#   Column(name = 'pubMedUrl', columnType = 'LINK', maximumSize = 50),
#   Column(name = 'publicationTitle', columnType = 'STRING', maximumSize = 203),
#   Column(name = 'publicationYear', columnType = 'INTEGER', maximumSize = 4),
#   Column(name = 'keywords', columnType = 'STRING', maximumSize = 243),
#   Column(name = 'theme', columnType = 'STRING_LIST', maximumSize = 27),
#   Column(name = 'tumorType', columnType = 'STRING_LIST', maximumSize = 50),
#   Column(name = 'tissue', columnType = 'STRING_LIST', maximumSize = 26),
#   Column(name = 'assay', columnType = 'STRING_LIST', maximumSize = 60),
#   Column(name = 'grantName', columnType = 'STRING_LIST', maximumSize = 107),
#   Column(name = 'consortium', columnType = 'STRING_LIST', maximumSize = 5),
#   Column(name = 'grantType', columnType = 'STRING', maximumSize = 3)
# )
```

```{r}
# merged_pub_schema <- Schema(name = "Portal - Publications Merged (test 3)", 
#                             columns = merged_pub_cols, 
#                             parent = "syn7080714")
# merged_pub_schema
```

```{r}
# merged_pub_table <- Table(merged_pub_schema, merged_formatted_pub_df)
# merged_pub_table <- synStore(merged_pub_table)
```

```{r}
merged_pub_table <- update_table("syn21868591", merged_formatted_pub_df)
```



## Tools - merged table

```{r}
db_tool_df <- get_table_df("syn21645208", cache = FALSE)

db_description_tool <- get_table_df("syn21918273", cache = FALSE)
db_datatype_tool <- get_table_df("syn21683485", cache = FALSE)
db_language_tool <- get_table_df("syn21683497", cache = FALSE)
db_link_tool <- get_table_df("syn21930556", cache = FALSE)
```

```{r}
tool_list_cols <- c(
  "grantName", 
  "theme", 
  "consortium",
  "inputDataType",
  "outputDataType"
)
```

```{r}
merged_tool_df <- db_tool_df %>% 
  select(-one_of(property_cols)) %>% 
  rename(toolId = id, toolName = displayName) %>%
  left_join(db_datatype_tool, by = "toolId") %>% 
  left_join(db_language_tool, by = "toolId") %>% 
  left_join(db_link_tool, by = "toolId") %>% 
  left_join(
    db_grant_df %>% 
      select(grantId = id, grantName = name, grantType, consortiumId), 
    by = "grantId"
  ) %>% 
  left_join(db_theme_grant, by = "grantId") %>% 
  left_join(
    db_theme_df %>% 
      select(themeId = id, theme = displayName),
    by = "themeId"
  ) %>% 
  left_join(
    db_consortium_df %>% 
      select(consortiumId = id, consortium = displayName)
  ) %>% 
  select(toolId, toolName, dataType, role, softwareLanguage,
         homepageUrl = url, toolType,
         theme, grantId, grantName, consortium) %>%
  distinct() %>% 
  pivot_wider(names_from = role, values_from = dataType) %>% 
  select(-`NA`) %>% 
  unnest(c("input")) %>% 
  unnest("output") %>% 
  rename_at(c("input", "output"), ~ str_c(., "DataType", sep = "")) 
    
merged_tool_df
```

```{r}
merged_formatted_tool_df <- merged_tool_df %>%
  group_by(toolId, toolName, homepageUrl, toolType) %>%
  summarize(
    grantId = str_c(unique(grantId), collapse = ", "),
    grantName = str_c(unique(grantName), collapse = ", "),
    inputDataType = str_c(unique(inputDataType), collapse = ", "),
    outputDataType = str_c(unique(outputDataType), collapse = ", "),
    softwareLanguage = str_c(unique(softwareLanguage), collapse = ", "),
    theme = str_c(unique(theme), collapse = ", "),
    consortium = str_c(unique(consortium), collapse = ", ")
  ) %>%
  ungroup() %>%
  # rowwise() %>%
  # mutate_at(tool_list_cols, ~ csv_str_to_json(.)) %>%
  # ungroup() %>%
  distinct()

merged_formatted_tool_df
```

```{r}
# merged_tool_cols <- list(
#    Column(name = 'toolName', columnType = 'STRING', maximumSize = 30),
#    Column(name = 'inputDataType', columnType = 'STRING_LIST', maximumSize = 30),
#    Column(name = 'outputDataType', columnType = 'STRING_LIST', maximumSize = 30),
#    Column(name = 'softwareLanguage', columnType = 'STRING_LIST', maximumSize = 20),
#    Column(name = 'theme', columnType = 'STRING_LIST', maximumSize = 50),
#    Column(name = 'grantName', columnType = 'STRING', maximumSize = 160),
#    Column(name = 'consortium', columnType = 'STRING', maximumSize = 30),
#    Column(name = 'grantType', columnType = 'STRING', maximumSize = 10)
# )
```

```{r}
# merged_tool_schema <- Schema(name = "Portal - Tools Merged",
#                            columns = merged_tool_cols,
#                            parent = "syn7080714")
# merged_tool_schema
```

```{r}
# merged_tool_table <- Table(merged_tool_schema, merged_tool_df)
# merged_tool_table <- synStore(merged_tool_table)
```

```{r}
merged_tool_syntable <- update_table("syn21930566", merged_formatted_tool_df)
```


