---
title: "R Notebook"
output: html_notebook
---

```{r}
library(synapser)
library(syndccutils)
library(tidyverse)
library(parcats)

source("summary_viz.R")
source("ncbi_lookup.R")
```


```{r}
plot_keys <- list(
  assay = "Assay", 
  tumorType = "Tumor Type",
  Theme = "Theme"
)

dataset_datafile_df <- min_dataset_df %>% 
  filter(id %in% nc_datasets) %>% 
  select(datasetId = id, Theme) %>% 
  left_join(min_datafile_df, by = "datasetId") 

dataset_datafile_df %>%
  distinct(id, datasetId, assay, tumorType, Theme) %>% 
  plot_counts_by_annotationkey(
    annotation_keys = plot_keys,
    label = "File"
  )
```

```{r}
dataset_datafile_df %>% 
  select(datasetId, id) %>% 
  group_by(datasetId) %>% 
  tally(name = "files") %>% 
  ggplot(aes(x = files)) + 
  geom_histogram() +
  scale_x_log10()
```


```{r}
plot_keys <- list(
  assay = "Assay",
  # study = "Study",
  tumorType = "Tumor Type",
  Theme = "Theme"
)
dataset_datafile_df %>% 
  group_by(.dots = names(plot_keys)) %>% 
  tally() %>% 
  plot_counts_by_annotationkey(
    annotation_keys = plot_keys, 
    label = "Dataset"
  )
```


```{r}
csbc_connect_df <- csbc_pub_df %>%
  select(Theme, experimentalStrategy, diseaseType, center = `CSBC PSON Center`) %>%
  # filter(complete.cases(.)) %>%
  filter(!is.na(Theme)) %>% 
  mutate(experimentalStrategy = str_split(experimentalStrategy, ";")) %>%
  unnest(experimentalStrategy) %>%
  mutate(experimentalStrategy = str_split(experimentalStrategy, ",")) %>%
  unnest(experimentalStrategy) %>%
  mutate(experimentalStrategy = str_trim(experimentalStrategy)) %>% 
  mutate(Theme = str_split(Theme, ",")) %>%
  unnest(Theme) %>%
  mutate(Theme = str_trim(str_to_lower(Theme))) %>% 
  # select(-center) %>% 
  # distinct() %>% 
  # mutate(center = row_number()) %>% 
  filter(!is.na(experimentalStrategy),
         !experimentalStrategy %in% c("Not Applicable", "Unspecified")) %>% 
  filter(!is.na(diseaseType),
         !diseaseType %in% c("Not Applicable", "Unspecified", "Pan-cancer")) %>% 
  filter(!is.na(center)) %>% 
  select(Theme, Center = center, Assay = experimentalStrategy, `Tumor Type` = diseaseType)
  # select(-Assay) %>% 
  # distinct()

# ?parcats::parcats

plot_sankey(csbc_connect_df, "Assay")
```


```{r}
connect_counts <- csbc_connect_df %>% 
  group_by_all() %>% 
  tally() %>% 
  ungroup() %>% 
  # left_join(select(min_center_df, id, institution), by = c("Center" = "id")) %>% 
  # mutate(institution = str_split(institution, ",")) %>%
  # unnest(institution) %>%
  # mutate(institution = str_trim(institution)) %>% 
  select(-Center) %>% 
  I

connect_nodes <- connect_counts %>% 
  select(-n) %>% 
  ungroup() %>% 
  pivot_longer( cols = c(Theme, Assay, diseaseType)) %>% 
  select(ID = value, Type = name) %>% 
  distinct() %>% 
  arrange(Type)

n_vars <- ncol(connect_counts) - 1


connect_df <- combn(1:n_vars, 2) %>% 
  array_branch(margin = 2) %>% 
  map(function(idx) {
    tmp_df <- connect_counts[, c(1,2,3)] %>% 
      mutate(obs = row_number())
    tmp_df[, c(idx, n_vars + 1)] %>% 
      set_names(c("V1", "V2", "obs"))
  }) %>% 
  bind_rows() %>% 
  left_join(connect_nodes, by = c("V1" = "ID")) %>% 
  arrange(Type) %>% 
  select(-Type) %>%
  distinct() %>%
  as_tibble() %>% 
  as.data.frame() 


g <- igraph::graph_from_data_frame(
  connect_df, 
  directed = F,
  vertices = connect_nodes)

g
clr <- as.factor(igraph::V(g)$Type)
levels(clr) <- ggthemes::colorblind_pal()(4)
igraph::V(g)$color <- as.character(clr)
igraph::V(g)$size <- igraph::degree(g)*5
edgebundleR::edgebundle(g, tension = 0.8, padding = 100)
```


```{r}
min_center_df %>% 
  rename(centerId = id) %>% 
  filter(!is.na(grantType)) %>% 
  filter(grantType != "U24") %>% 
  group_by(consortium, grantType) %>% 
  tally(name = "grants")
```


```{r}
# c("28465358", pmids$pmid[1:20]) %>% 
pub_data <- pmids$pmid %>% 
  set_names(.) %>% 
  map(get_pub_dbxrefs) %>% 
  discard(is.null) %>% 
  map_df(enframe, .id = "pmid") %>% 
  spread(name, value)
```


```{r}
min_center_df %>% 
  rename(centerId = id) %>% 
  filter(!is.na(grantType), !is.na(theme)) %>%
  filter(grantType != "U24") %>%
  mutate(theme = str_trim(theme)) %>%
  # mutate(theme = str_split(theme, ";")) %>%
  # unnest(theme) %>%
  # mutate(theme = str_to_lower(theme)) %>%
  # filter(!is.na(theme)) %>%
  # mutate(theme = str_trim(theme)) %>%
  # filter(theme != "") %>% 
  select(centerId, consortium, grantType, theme)
```

```{r}
min_center_df %>% 
  rename(centerId = id) %>% 
  filter(!is.na(grantType), !is.na(theme)) %>%
  filter(grantType != "U24") %>%
  # select(centerId, grantType, theme) %>% 
  mutate(theme = str_trim(theme)) %>%
  mutate(theme = str_split(theme, ";")) %>%
  unnest(theme) %>%
  mutate(theme = str_to_lower(theme)) %>%
  filter(!is.na(theme)) %>%
  mutate(theme = str_trim(theme)) %>%
  filter(theme != "") %>% 
  select(centerId, consortium, grantType, theme) %>%
  # group_by(consortium, grantType, theme) %>% 
  # tally(name = "grants") %>%
  plot_sankey("centerId") %>%
  # view() %>% 
  I

```


```{r}
min_grant_df %>% 
  rename(grantId = id) %>% 
  filter(!is.na(grantType), !is.na(theme)) %>%
  filter(grantType != "U24") %>%
  mutate(theme = str_trim(theme)) %>%
  mutate(theme = str_split(theme, ";")) %>%
  unnest(theme) %>%
  mutate(theme = str_to_lower(theme)) %>%
  filter(!is.na(theme)) %>%
  mutate(theme = str_trim(theme)) %>%
  filter(theme != "") %>% 
  select(grantId, consortium, grantType, theme) %>%
  left_join(select(min_project_df, grantId, projectId = id, label)) %>% 
  select(projectId, consortium, grantType, grant = grantId, label) %>% 
  distinct() %>% 
  mutate(label = str_replace(label, " [0-9]", "")) %>% 
  rename(projectType = label) %>% 
  # group_by(consortium, grantType, grant, projectType) %>%
  # tally(name = "projects") %>%
  # view() %>% 
  plot_sankey("projectId") %>%
  I
```






