---
title: "Portal Cleanup"
output: html_notebook
---

```{r}
library(reticulate)
library(dccvalidator)
library(tidyverse)
library(purrrogress)

# source("../R/synapse_db.R")

use_condaenv("csbc-pson-dcc", required = TRUE)
synapseclient <- reticulate::import("synapseclient")
syn <- synapseclient$Synapse()
syntab <- reticulate::import("synapseclient.table")
synfile <- synapseclient$File
syn$login()
```


```{r}
tibble(id = c("ICBP", "TEC")) %>% 
  create_entities("syn21630050", syn, synfile)

```

## Grants

```{r}
merged_grant_df <- dccvalidator::get_synapse_table("syn21918972", syn)
```

```{r}
db_institution_df <- dccvalidator::get_synapse_table("syn21905891", syn)
```

```{r}
merged_grant_df %>%
  select(-institutionAlias) %>% 
  # select(grantId, institutionId) %>% 
  separate_rows(institutionId, sep = ",") %>% 
  mutate_all(~ str_trim(.)) %>% 
  left_join(select(db_institution_df, institutionId = id, institutionAlias = displayName),
            by = "institutionId") %>%
  group_by_at(vars(-one_of(c("institutionId", "institutionAlias")))) %>%
  summarize_all(~ str_c(., collapse = ", ")) %>%
  ungroup() %>%
  mutate(institutionAlias = map_chr(institutionAlias, .delim_str_to_json)) %>%
  update_synapse_table("syn21918972", ., syn, syntab)
```


```{r}
merged_grant_df %>% 
  select(grantId, institutionId) %>% 
  separate_rows(institutionId, sep = ",") %>% 
  mutate_all(str_trim) %>% 
  distinct() %>% 
  I %>% 
  update_synapse_table("syn21905912", ., syn, syntab)
```

```{r}
db_institution_df <- dccvalidator::get_synapse_table("syn21905891", syn)
```

```{r}
merged_grant_cleaned <- merged_grant_df %>% 
  separate_rows(institutionId, institution, sep = "\\|") %>% 
  mutate_all(str_trim) %>% 
  distinct() %>% 
  arrange(institution) %>% 
  mutate(institutionId = case_when(
    institution == "University of Pennsylvania" ~ "syn21905883",
    institution == "University of Virginia" ~ "syn21905886",
    institution == "University of Colorado Denver" ~ "",
    institution == "University of Delaware" ~ "",
    institution == "Pacific Northwest National Laboratory" ~ "",
    institution == "Massachusetts Institute of Technology" ~ "syn21905863",
    institution == "The Hebrew University of Jerusalem" ~ "",
    TRUE ~ institutionId
  )) %>% 
  mutate(institution = str_replace(institution, "^The ", "")) %>% 
  # filter(institutionId == "") %>% 
  left_join(select(db_institution_df, id, institution = fullName), by = "institution") %>%
  mutate(institutionId = ifelse(institutionId == "", id, institutionId)) %>%
  select(-id) %>%
  distinct() %>% 
  group_by_at(vars(-contains("institution"))) %>%
  summarize(
    institutionId = str_c(unique(institutionId), collapse = ", "),
    institution = str_c(unique(institution), collapse = " | ")
  ) %>% 
  ungroup() %>% 
  mutate_all(~ ifelse(str_detect(., "Not Applicable"), NA, .)) %>%
  mutate_all(~ ifelse(str_detect(., '"Not Applicable"'), NA, .)) %>%
  mutate_all(~ ifelse(str_detect(., "^NA$"), NA, .)) %>%
  mutate_all(~ ifelse(str_detect(., '\\["NA"\\]'), NA, .)) %>%
  mutate_all(~ ifelse(str_detect(., '"NA"'), NA, .)) %>%
  I
merged_grant_cleaned
```


```{r}
merged_grant_syntable <- update_synapse_table("syn21918972", merged_grant_cleaned, syn, syntab)
```


## Projects

```{r}
merged_project_df <- dccvalidator::get_synapse_table("syn21868602", syn)
```

```{r}
merged_project_cleaned <- merged_project_df %>% 
  mutate(theme = str_replace(theme, "Tumor Evolution", "Evolution")) %>% 
  mutate(theme = str_replace(theme, "metastasis", "Metastasis")) %>% 
  mutate(theme = str_replace(theme, "drug resistance/sensitivity", "Drug Resistance/Sensitivity")) %>% 
  mutate(theme = str_replace(theme, "microenvironment", "Microenvironment")) %>% 
  mutate_all(~ ifelse(str_detect(., "Not Applicable"), NA, .)) %>%
  mutate_all(~ ifelse(str_detect(., '"Not Applicable"'), "", .)) %>%
  mutate_all(~ ifelse(str_detect(., "^NA$"), NA, .)) %>%
  mutate_all(~ ifelse(str_detect(., '\\["NA"\\]'), "[]", .)) %>%
  mutate_all(~ ifelse(str_detect(., '"NA"'), "", .)) %>%
  # filter(projectId == "syn21645193") %>% 
  # update_synapse_table("syn21930566", ., syn, syntab) %>%
  I
 
merged_project_cleaned
```

```{r}
merged_project_syntable <- update_synapse_table("syn21868602", merged_project_cleaned, syn, syntab)
```

## Tools

```{r}
merged_tool_df <- dccvalidator::get_synapse_table("syn21930566", syn)
```

```{r}
merged_tool_cleaned <- merged_tool_df %>% 
  mutate(theme = str_replace(theme, "Tumor Evolution", "Evolution")) %>% 
  mutate_all(~ ifelse(str_detect(., "Not Applicable"), NA, .)) %>%
  mutate_all(~ ifelse(str_detect(., '"Not Applicable"'), "", .)) %>%
  mutate_all(~ ifelse(str_detect(., "^NA$"), NA, .)) %>%
  mutate_all(~ ifelse(str_detect(., '\\["NA"\\]'), "[]", .)) %>%
  mutate_all(~ ifelse(str_detect(., '"NA"'), "", .)) %>%
  mutate(homepageUrl = ifelse(is.na(homepageUrl), "", homepageUrl)) %>% 
  mutate(toolType = ifelse(is.na(toolType), "", toolType)) %>% 
  mutate(publicationId = ifelse(is.na(publicationId), "", publicationId)) %>% 
  mutate(publicationTitle = ifelse(is.na(publicationTitle), "", publicationTitle)) %>% 
  mutate(publication = ifelse(is.na(publication), "", publication))
 
merged_tool_cleaned
```

```{r}
merged_tool_syntable <- update_synapse_table("syn21930566", merged_tool_cleaned, syn, syntab)
```

## Datasets


```{r}
merged_dataset_df <- dccvalidator::get_synapse_table("syn21897968", syn)
```

```{r}
merged_dataset_cleaned <- merged_dataset_df %>% 
  mutate(theme = str_replace(theme, "Tumor Evolution", "Evolution")) %>% 
  mutate(theme = str_replace(theme, "metastasis", "Metastasis")) %>% 
  mutate(theme = str_replace(theme, "drug resistance/sensitivity", "Drug Resistance/Sensitivity")) %>% 
  mutate(theme = str_replace(theme, "microenvironment", "Microenvironment")) %>% 
  mutate(assay = str_replace(assay, "Whoe", "Whole")) %>% 
  mutate_all(~ ifelse(str_detect(., "Not Applicable"), NA, .)) %>%
  mutate_all(~ ifelse(str_detect(., '"Not Applicable"'), "", .)) %>%
  mutate_all(~ ifelse(str_detect(., "^NA$"), NA, .)) %>%
  mutate_all(~ ifelse(str_detect(., '\\["NA"\\]'), "[]", .)) %>%
  mutate_all(~ ifelse(str_detect(., '"NA"'), "", .)) %>%
  mutate(tumorType = ifelse(is.na(tumorType), "", tumorType)) %>% 
  # filter(datasetId == "syn21645193") %>% 
  # update_synapse_table("syn21930566", ., syn, syntab) %>%
  I
 
merged_dataset_cleaned
```

```{r}
merged_dataset_syntable <- update_synapse_table("syn21897968", merged_dataset_cleaned, syn, syntab)
```

## Publications

```{r}
merged_publication_df <- dccvalidator::get_synapse_table("syn21868591", syn)
```

```{r}
merged_publication_df %>% 
  select(-grantInstitution) %>% 
  mutate(grantId = map(grantId, json_to_list)) %>% 
  unnest(grantId) %>% 
  
  left_join(select(merged_grant_df, grantId, institutionId, institutionAlias, grantInstitution),
            by = "grantId") %>%
  # group_by_at(vars(-one_of(c("institutionId", "institutionAlias")))) %>%
  # summarize_all(~ str_c(., collapse = ", ")) %>%
  # ungroup() %>%
  # mutate(institutionAlias = map_chr(institutionAlias, .delim_str_to_json)) %>% 
  I
```


```{r}
merged_publication_cleaned <- merged_publication_df %>% 
  mutate_all(~ ifelse(str_detect(., "Not Applicable"), NA, .)) %>%
  mutate_all(~ ifelse(str_detect(., '"Not Applicable"'), "", .)) %>%
  mutate_all(~ ifelse(str_detect(., "^NA$"), NA, .)) %>%
  mutate_all(~ ifelse(str_detect(., '\\["NA"\\]'), "[]", .)) %>%
  mutate_all(~ ifelse(str_detect(., '"NA"'), "", .)) %>%
  mutate_at(c("doi", "keywords",
              "themeId", "theme", "datasetId", "dataset"),
            ~ ifelse(is.na(.), "", .)) %>%
  # mutate(tumorType = ifelse(is.na(tumorType), "", tumorType)) %>% 
  # mutate(doi = ifelse(is.na(doi), "", doi)) %>% 
  # mutate(keywords = ifelse(is.na(keywords), "", keywords)) %>% 
  # mutate(assay = ifelse(is.na(assay), "", assay)) %>% 
  # mutate(datasetId = ifelse(is.na(datasetId), "", datasetId)) %>% 
  # mutate(dataset = ifelse(is.na(dataset), "", dataset)) %>% 
  # filter(publicationId == "syn21645193") %>% 
  # update_synapse_table("syn21930566", ., syn, syntab) %>%
  I
 
merged_publication_cleaned
```

```{r}
merged_publication_syntable <- update_synapse_table("syn21868591", merged_publication_cleaned, syn, syntab)
```
